quarkus:
  profile: dev
  http:
    port: 8080
    limits:
      max-body-size: 12M
  # https://quarkus.io/guides/datasource
  datasource:
    db-kind: mysql
    db-version: 8.0.27
    username: root
    password: abcUUddsef
    jdbc:
      url: jdbc:mysql://aliyun2:3306/db_test?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      max-size: 5
      min-size: 1
  # https://quarkus.io/guides/hibernate-orm
  hibernate-orm:
    database:
      generation: none
    sql-load-script: no-file
  package:
    jar:
      type: UBER_JAR
    runner-suffix: -runner
  thread-pool:
    max-threads: 3
    queue-size: 16



hello: hello,dev

greeting:
  title: show properties usage
  version: v1
