quarkus:
  profile: dev
  http:
    port: 8080
  datasource:
    db-kind: mysql
    db-version: 5.7.0
    username: root
    password: abcUUddsef
    jdbc:
      url: jdbc:mysql://aliyun2:3306/db_test?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      max-size: 5
      min-size: 1
  package:
    jar:
      type: uber-jar
    runner-suffix: -runner

hello: hello,dev
