quarkus:
  application:
    name: api2-web
  profile: dev
  http:
    # 不配置host，只能 localhost 访问
    # 因为 前端页面是在另一个服务器上（使用vscode + remote development），要访问本服务
    host: 0.0.0.0
    port: 20002
    root-path: "/api2"
    limits:
      max-body-size: 12M
  # https://quarkus.io/guides/datasource
  datasource:
    db-kind: mysql
    #    db-kind: other
    db-version: 8.0.27
    username: root
    password: abcUUddsef
    jdbc:
      #      driver: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:mysql://aliyun-test:3306/eblog?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      #      url: jdbc:p6spy:mysql://aliyun-test:3306/eblog?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      max-size: 5
      min-size: 1
  # https://quarkus.io/guides/hibernate-orm
  hibernate-orm:
    packages: cn.valuetodays.api2
    database:
      generation: none
    sql-load-script: no-file
    log:
      # the printed sql is containing ?
      sql: false
  package:
    jar:
      type: UBER_JAR
    runner-suffix: -runner
  thread-pool:
    max-threads: 3
    queue-size: 16
  redis:
    hosts: redis://localhost:6379
    password: 'abc123'
    timeout: 10s


hello: hello,dev

greeting:
  title: show properties usage
  version: v1

nats:
  server: nats://aliyun-test:4222
  token: zFFjQ6QjgP9tp3GNGb9PL
