hello: hello,prod

quarkus:
  redis:
    hosts: redis://aliyun2:6379
    password: 'abc123'
  datasource:
    username: root
    password: abcUUddsef
    jdbc:
      url: jdbc:p6spy:mysql://aliyun2:3306/eblog?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
#      url: jdbc:mysql://aliyun2:3306/eblog?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true

nats:
  server: nats://aliyun2:4222
  token: by-command-line
