hello: hello,prod

quarkus:
  redis:
    hosts: redis://aliyun-prod:6379
    password: 'abc123'
  datasource:
    db-kind: mysql
    #    db-kind: other
    db-version: 8.0.27
    username: root
    password: abcUUddsef
    jdbc:
      #      driver: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:mysql://aliyun-prod:3306/eblog?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
#      url: jdbc:p6spy:mysql://aliyun-prod:3306/eblog?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
  hibernate-orm:
    log:
      # the printed sql is containing ?
      sql: false
nats:
  server: nats://aliyun2:4222
  token: by-command-line

jasypt:
  encryptor:
    password: 'from-command-line'
