quarkus:
  application:
    name: api2-web
  profile: dev
  http:
    # 不配置host，只能 localhost 访问
    # 因为 前端页面是在另一个服务器上（使用vscode + remote development），要访问本服务
    host: 0.0.0.0
    port: 20002
    root-path: "/api2"
    limits:
      max-body-size: 12M
  # https://quarkus.io/guides/datasource
  datasource:
    db-kind: mysql
    #    db-kind: other
    db-version: 8.0.27
    username: root
    password: abcUUddsef
    jdbc:
      #      driver: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:mysql://aliyun-test:3306/eblog?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      #      url: jdbc:p6spy:mysql://aliyun-test:3306/eblog?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      max-size: 5
      min-size: 1
  # https://quarkus.io/guides/hibernate-orm
  hibernate-orm:
    # https://docs.jboss.org/hibernate/orm/6.6/dialect/dialect.html
    #    dialect: MySQL
    dialect: cn.valuetodays.api2.web.extend.NoEscapeMySQLDialect
    schema-management:
      strategy: none
    packages: cn.valuetodays
    database:
      #      generation: none
      version-check:
        enabled: false
    sql-load-script: no-file
    log:
      # the printed sql is containing ?
      sql: true
    validate-in-dev: false
    validation:
      mode: none
  package:
    jar:
      type: UBER_JAR
    runner-suffix: -runner
  thread-pool:
    max-threads: 3
    queue-size: 16
  redis:
    hosts: redis://localhost:6379
    password: 'abc123'
    timeout: 10s
    database: 0


hello: hello,dev

nats:
  server: nats://aliyun-test:4222
  token: zFFjQ6QjgP9tp3GNGb9PL


vt:
  github:
    username: valuetodays
    email: from-env11
    git-token: from-env11
  vocechat:
    base-path: http://vocechat.valuetodays.cn
    url-send-to-group: ${vt.vocechat.base-path}/api/bot/send_to_group/
    url-send-to-user: ${vt.vocechat.base-path}/api/bot/send_to_user/
    api-key: a7c49bf36ecaa1fa709f877941e96c3a02c716965f7dc405aa09cb958d78c7bd7b22756964223a322c226e6f6e6365223a226d356162442f65565547594141414141426857634c7771743245365a56576a4f227d
    bot-fortune-api-key: d89f3c09119950ca10b98b100326ea851bde454de092b67b480bd0163106bbc57b22756964223a332c226e6f6e6365223a22336c485a42776446536d6741414141414966364855766c636a422f7a47545249227d

jasypt:
  encryptor:
    password: 'aQzpbofz0oil1'
