version: "3"

services:
  quote-web:
    image: openjdk:21-jdk
    container_name: quarkus-demo
    ports:
      - "58080:8080"
    volumes:
      - "/opt/workbench/:/root/workbench/"
    command: ["java", "-Ddebug=false",
              "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005",
              "-Dfile.encoding=utf8",
              "-XX:+UseZGC", "-XX:+ZGenerational",
              "-Xmx512m", "-Xms512m", "-Xss512k",
#              "-XX:+UseG1GC",
#              "-XX:+PrintGCDetails", "-XX:+PrintGC",
#              "-XX:+PrintGCTimeStamps",
#              "-Xloggc:/root/workbench/api/gclog/gc.log",
              "-Dquarkus.profile=prod",
              "-DLOG_DIR=/root/workbench/logs/quarkus-demo-runner",
              "-jar", "/root/workbench/deploy/quarkus-demo-runner.jar"]
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.utf8
    extra_hosts:
      - aliyun:172.23.117.235
      - aliyun2:172.23.117.235
